// <auto-generated/>
// Copyright (c) Lucas Girouard-Stranks (https://github.com/lithiumtoast). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the Git repository root directory (https://github.com/lithiumtoast/my-msbuild) for full license information.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
	"Microsoft.Naming",
	"CA1051:DoNotDeclareVisibleInstanceFields",
	Justification = "'fields should be as an implementation detail' is wrong; fields are data and developers need to work with data.")]

[assembly: SuppressMessage(
	"Microsoft.Naming",
	"CA1720:IdentifiersShouldNotContainTypeNames",
	Justification = "Developers should know the difference between a builtin type and an identifier on a type with the same name as a builtin type.")]

[assembly: SuppressMessage(
	"Microsoft.Naming",
	"CA1711:IdentifiersShouldNotHaveIncorrectSuffix",
	Justification = "Naming of types with a certain suffix like 'Exception' or 'Collection' should not reserved just for Microsoft; developers should be free to name types as they wish within reason.")]

[assembly: SuppressMessage(
	"Microsoft.Naming",
	"CA1822:MarkMembersAsStatic",
	Justification = "If something could be static but it's not then the developer made a conscience choice.")]
	
[assembly: SuppressMessage(
	"ReSharper",
	"MemberCanBeMadeStatic.Local",
	Justification = "If something could be static but it's not then the developer made a conscience choice.")]

[assembly: SuppressMessage(
	"ReSharper",
	"MemberCanBeMadeStatic.Global",
	Justification = "If something could be static but it's not then the developer made a conscience choice.")]