on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  dotnet-job:
    runs-on: ubuntu-latest
    name: ".NET"
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v1
        with:
          repository: '${{ github.repository }}'
          solution-or-project: './src/cs/production/MSBuild.Tools/MSBuild.Tools.csproj'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: true
          publish-environment: 'staging'
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'